services:
  postgres:
    image: postgres:16
    container_name: clickmart-postgres
    expose:
      - 5432
    volumes:
      - ./postgresql/data:/var/lib/postgresql/data
      - ./postgresql/initdb:/docker-entrypoint-initdb.d
    env_file:
      - .env
    networks: 
      - clickmart-network
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '1'
        reservations:
          memory: 512M
          cpus: '0.5'
  pgadmin:
    image: dpage/pgadmin4
    container_name: clickmart-pgadmin
    ports:
      - "5050:80"
    volumes:
      - ./pgadmin/data:/var/lib/pgadmin
    env_file:
      - .env
    networks:
      - clickmart-network
    restart: always
    healthcheck:
      test: ["CMD", "wget", "-O", "-", "http://localhost:80/misc/ping"]
      interval: 30s
      timeout: 10s
      start_period: 160s
      retries: 3
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
        reservations:
          memory: 256M
          cpus: '0.25'
  logstash:
    image: logstash:8.15.2
    container_name: clickmart-logstash
    expose:
      - 5044
    volumes:
      - ./logstash/pipelines:/usr/share/logstash/pipeline
    networks:
      - clickmart-network
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9600/_node/stats"]
      interval: 30s
      timeout: 10s
      retries: 5
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '1'
        reservations:
          memory: 512M
          cpus: '0.5'
  elasticsearch:
    image: elasticsearch:8.15.2
    container_name: clickmart-elasticsearch
    ulimits:
      memlock:
        soft: -1
        hard: -1
    expose:
      - 9200
    volumes:
      - ./elasticsearch/data:/usr/share/elasticsearch/data
    env_file:
      - .env
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    networks:
      - clickmart-network
    restart: always
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9200/_cluster/health" ]
      interval: 30s
      timeout: 10s
      retries: 5
    deploy:
      resources:
        limits:
          memory: 2G
          cpus: '2'
        reservations:
          memory: 1G
          cpus: '1'
  kibana:
    image: kibana:8.15.2
    container_name: clickmart-kibana
    ports:
      - "5601:5601"
    env_file:
      - .env
    networks:
      - clickmart-network
    depends_on:
      - elasticsearch
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5601/app/kibana"]
      interval: 30s
      timeout: 10s
      retries: 5
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '1'
        reservations:
          memory: 512M
          cpus: '0.5'
  nginx:
    image: nginx:1.27.1
    container_name: clickmart-nginx
    ports:
      - "8000:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/configs:/etc/nginx/conf.d:ro
      - ./nginx/logs:/var/log/nginx
    networks:
      - clickmart-network
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 30s
      timeout: 10s
      retries: 5
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: '0.5'
        reservations:
          memory: 128M
          cpus: '0.25'

networks:
  clickmart-network:
    name: clickmart-network